version: '3'

services:
   appwsc-qsallcomponent-jee-db:
      container_name: appwsc-qsallcomponent-jee-db
      image: appwsc-qsallcomponent-jee-db
         
      networks:
         - net    
   appwsc-qsallcomponent-jee-server:
      container_name: appwsc-qsallcomponent-jee-boot
      image: appwsc-qsallcomponent-jee-boot
      ports:
         - "9091:8080"
      depends_on:
         - appwsc-qsallcomponent-jee-db
      networks:
         - net
      volumes:
        - "/opt/docker-data/qsallcomponents/logs:/usr/local/tomcat/logs"

networks:
   net: