version: '3'

services:
   appwsc-qsallcomponent-jee-development-preview-db:
      container_name: appwsc-qsallcomponent-jee-development-preview-db
      image: appwsc-qsallcomponent-jee-development-preview-db
         
      networks:
         - net    
   appwsc-qsallcomponent-jee-development-preview-server:
      container_name: appwsc-qsallcomponent-jee-development-preview-boot
      image: appwsc-qsallcomponent-jee-development-preview-boot
      ports:
         - "9092:8080"
      depends_on:
         - appwsc-qsallcomponent-jee-development-preview-db
      networks:
         - net
      volumes:
        - "/opt/docker-data/appwsc-qsallcomponents-development-preview/logs:/usr/local/spring-boot/logs"

networks:
   net: