ontimize:
  corsfilter:
    enabled: true
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders: "*"
        exposedHeaders: ["X-Auth-Token","Content-disposition","X-Requested-With"]
        allowedMethods:
          - GET
          - POST
          - PUT
          - OPTIONS
          - DELETE
  jdbc:
    name_convention: upper
    sqlhandler: hsqldb
    sql_condition_processor:
      upper_string: true
      upper_like: true
  security:
    mode: default
    userInformationService:
      userRepository: OCLoginProfilesDao
      queryId: login
      userLoginColumn: USER_
      userPasswordColumn: PASSWORD
      otherData:
        - NAME
        - SURNAME
        - EMAIL
        - NIF
        - USERBLOCKED
        - LASTPASSWORDUPDATE
        - FIRSTLOGIN
    userRoleInformationService:
      userRoleRepository: OCLoginProfilesDao
      queryId: userRoles
      roleLoginColumn: USER_
      roleNameColumn: ROLENAME
    roleInformationService:
      roleRepository: OCLoginProfilesDao
      roleNameColumn: ROLENAME
      serverPermissionQueryId: serverPermissions
      serverPermissionNameColumn: PERMISSION_NAME
      clientPermissionQueryId: clientPermissions
      clientPermissionColumn: XMLCLIENTPERMISSION
  remote_configuration: true
  export:
    extension: xlsx
    url: /export
endpoints:
  api:
    enabled: true
logging:
  level:
    root: info
server:
  port: 8080
  servlet:
    context-path: /qsallcomponents-jee
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json, application/xml
spring:
  autoconfigure:
    exclude: |
      org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    jdbcUrl: jdbc:hsqldb:hsql://localhost:9013/templateDB
    username: SA
    password:
    initialSize: 10
    testOnBorrow: true
  devtools:
    livereload:
      enabled: false
  http:
    multipart:
      maxFileSize: 1Mb
      maxRequestSize: 1Mb
  main:
    banner-mode: 'off'
  session:
    store-type: none

