ontimize:
  corsfilter:
    enabled: true
  dms:
    engine: odms
    base-path: file:/C:/applications/QSAllComponents_Jee/dms
  report:
    enable: true
    engine: database
  export:
    enable: true
    url: /export
    extension: xlsx
  save-config: true
  save-config-dao: ConfigsDao
  globalcors:
    cors-configurations:
      '[/**]':
        allowed-origins: "*"
        allowed-headers: "*"
        exposed-headers: ["X-Auth-Token","Content-disposition","X-Requested-With"]
        allowed-methods:
          - GET
          - POST
          - PUT
          - OPTIONS
          - DELETE
  jdbc:
    name-convention: upper
    sqlhandler: hsqldb
    sql-condition-processor:
      upper-string: true
      upper-like: true
  security:
    mode: default
    user-information-service:
      user-repository: OCLoginProfilesDao
      query-id: login
      user-login-column: USER_
      user-password-column: PASSWORD
      other-data:
        - NAME
        - SURNAME
        - EMAIL
        - NIF
        - USERBLOCKED
        - LASTPASSWORDUPDATE
        - FIRSTLOGIN
    user-role-information-service:
      user-role-repository: OCLoginProfilesDao
      query-id: userRoles
      role-login-column: USER_
      role-name-column: ROLENAME
    role-information-service:
      role-repository: OCLoginProfilesDao
      role-name-column: ROLENAME
      server-permission-query-id: serverPermissions
      server-permission-name-column: PERMISSION_NAME
      client-permission-query-id: clientPermissions
      client-permission-column: XMLCLIENTPERMISSION
  remote-configuration: true
endpoints:
  api:
    enabled: true
logging:
  level:
    org.springframework.security.web.firewall.HttpStatusRequestRejectedHandler: DEBUG
    root: info
server:
  port: 8080
  servlet:
    context-path: /qsallcomponents-jee
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json, application/xml
spring:
  autoconfigure:
    exclude: |
      org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    jdbc-url: jdbc:hsqldb:hsql://localhost:9013/templateDB
    username: SA
    password:
    initial-size: 10
    test-on-borrow: true
  devtools:
    livereload:
      enabled: false
  http:
    multipart:
      max-file-size: 1Mb
      max-request-size: 1Mb
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  session:
    store-type: none

